# Site settings
author: Kishor Shankaranarayan
title: 
header-img: img/home-bg.png
email: ksis1st@hotmail.com
copyright_name: Kishor Shankaranarayan
description: > # this means to ignore newlines until "baseurl:"
  
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  ksis1st

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
